AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
Metrics/LineLength:
  Max: 100
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
AlignParameters:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Max: 100
Metrics/AbcSize:
  Max: 20
MethodLength:
  CountComments: false
  Max: 15
ClassLength:
  CountComments: false
  Max: 200
Style/AlignHash:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/DotPosition:
  EnforcedStyle: leading
Naming/FileName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false